
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Dar permisos de ejecución al script
      run: chmod +x test.sh

    - name: Ejecutar pruebas
      run: ./test.sh
